### ISSUE TITLE
Register Question model into Admin tool

### ISSUE THREAD

**Issue by tangziyi001** [new-dawn/new_dawn_server#37]
Question model is supposed to be created by admins. So it is reasonable to add them into admin tool.
Mimic the admin.py in users directory. Figure out how to add question model in admin.py in questions directory.

**Comment by duckmoll** [comment]
I heard xadmin for django admin is a pretty UI replacement.

**Comment by tangziyi001** [comment]
let's not worry about adminUI yet since it should be (P4) at this time. As a starter let's just add it to the default admin tool.
after completing this task, will let you work more on API tasks to get familiar with tastypie framework
