### ISSUE TITLE
Write GET API for cities

### ISSUE THREAD

**Issue by tangziyi001** [new-dawn/new_dawn_server#38]
It would be ideal if iOS can get a list of normalized city names from server side for user to choose during registration, instead of letting users to input a random char field. We can do that by exposing a GET API. Take a look at the current GET resources in resources.py and figure out to how to build a API like that.

You also need to integrate third-party API to get that city list.

This is a low-pri task (for MVP we can just hardcode the city names in iOS), but would be helpful in the future and help you ramp up tastypie resources and how to integrate third-party APIs

**Comment by tangziyi001** [comment]
Notice that this won't involve any data model changes. We will still save char field in data model, but by letting iOS to get a list of city names as options, the char field we are going to use can be normalized in application level.

**Comment by duckmoll** [comment]
Shouldn't I split the city_preference to country/city?

**Comment by duckmoll** [comment]
OK! Regarding point 2, you intend to add city resource to account instead of profile?

**Comment by tangziyi001** [comment]
We can add in account for now since I think preferred city is more like a private info. We can still dehydrate it if we want

**Comment by duckmoll** [comment]
Sure thing.

**Comment by tangziyi001** [comment]
As a side note, try to submit three PR (model, api, prepend_url api) separately. This is a good practice of incremental development.

**Comment by tangziyi001** [comment]
Next step is to hardcode a dict of cities and prepend_url to expose a get city name list API. You can mimic how other prepended  url wrapped view works and use ClientResponse to construct your return value

**Comment by duckmoll** [comment]
Yea, I'm stuck at writing the test, where I can get result from local API Tester Software, but get 'error': 'Request is not valid JSON.' from test case....

**Comment by duckmoll** [comment]
Will open a PR
