### ISSUE TITLE
API request: phone_verify/get_country_code_map

### ISSUE THREAD

**Issue by tangziyi001** [new-dawn/new_dawn_server#72]
Write an API to get country code map. Add a constants file and put a dict of country_name -> country_code there. Return the whole dict as a client response.

This is used for user to select the country code they want during phone verification

You should add that in `users/api/resources.py`

**Comment by duckmoll** [comment]
Should I skip this issue since Tianchu already has some setups in ios?

**Comment by tangziyi001** [comment]
Yep
