### ISSUE TITLE
Prepend_url to write an API to get all non-user-defined questions (a list of string). 

### ISSUE THREAD

**Issue by duckmoll** [new-dawn/new_dawn_server#74]
This is used to bootstrap user's answer question page.

**Comment by tangziyi001** [comment]
Thanks for opening this issue! Since Question is already a data model, Can you try let Question resource to allow filter with user-defined field? So we can directly use Tastypie API to get those questions.

**Comment by tangziyi001** [comment]
So ideally we can just use it’s Tastypie API like api/v1/questions/?user-defined=true to query those non-user-defined questions
